server:
  env: "debug"
  address: "127.0.0.1"
  port: 8888
  gracefulShutdownPeriod: 30

db:
  port: "27017"
  host: "127.0.0.1"
  database: "tui"
  user: "tui"
  password: "tui312"
  migrationsPath: "./internal/migrations"
